sudo: required

services:
- docker

before-install:
- docker build -t andeqt/loginapp


script:
- docker run andeqt/loginapp npm test

after-success:
    - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_ID" --password-stdin

    -docker push Automation12345/practise_project